import { prisma } from "../lib/prisma";

type IngredientSeed = {
  ingredientName: string;
  normalizedName: string;
  aliases?: string[];
  containsGluten?: boolean;
  containsDairy?: boolean;
  containsEgg?: boolean;
  containsSoy?: boolean;
  containsNuts?: boolean;
  containsShellfish?: boolean;
  containsSesame?: boolean;
  isVegetarian?: boolean | null;
  isVegan?: boolean | null;
  confidence?: string;
  notes?: string;
  source?: string;
  verified?: boolean;
};

const INGREDIENT_RULES: IngredientSeed[] = [
  // DAIRY CORE
  {
    ingredientName: "Butter",
    normalizedName: "butter",
    aliases: ["sweet butter", "garlic butter", "vermont butter", "brown butter"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Butter contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Milk",
    normalizedName: "milk",
    aliases: ["whole milk", "low fat milk", "skim milk"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Milk contains dairy unless explicitly plant-based.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Cream",
    normalizedName: "cream",
    aliases: [
      "heavy cream",
      "whipping cream",
      "whipped cream",
      "sour cream",
      "cream sauce",
      "cream cheeses",
      "crema",
    ],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Cream contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Cheese",
    normalizedName: "cheese",
    aliases: [
      "cheeses",
      "cream cheese",
      "cheddar cheese",
      "swiss cheese",
      "domestic cheeses",
      "imported cheeses",
      "assorted cheeses",
    ],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Cheese contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Mozzarella",
    normalizedName: "mozzarella",
    aliases: ["fresh mozzarella", "mozzarella cheese"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Mozzarella contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Parmesan",
    normalizedName: "parmesan",
    aliases: ["parmigiano", "parmigiano reggiano"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Parmesan contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Ricotta",
    normalizedName: "ricotta",
    aliases: ["ricotta salata", "herbed ricotta"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Ricotta contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Feta",
    normalizedName: "feta",
    aliases: ["feta cheese"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Feta contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Goat Cheese",
    normalizedName: "goat cheese",
    aliases: ["chèvre"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Goat cheese contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Burrata",
    normalizedName: "burrata",
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Burrata contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Mascarpone",
    normalizedName: "mascarpone",
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Mascarpone contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Gorgonzola",
    normalizedName: "gorgonzola",
    aliases: ["blue cheese"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Blue cheeses contain dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Yogurt",
    normalizedName: "yogurt",
    aliases: ["yogurts", "greek yogurt", "individual yogurt"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Yogurt contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Ice Cream",
    normalizedName: "ice cream",
    aliases: ["gelato"],
    containsDairy: true,
    isVegetarian: true,
    isVegan: false,
    confidence: "high",
    notes: "Ice cream usually contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Custard",
    normalizedName: "custard",
    containsDairy: true,
    containsEgg: true,
    confidence: "high",
    notes: "Custard typically contains dairy and egg.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Béchamel",
    normalizedName: "bechamel",
    aliases: ["béchamel"],
    containsDairy: true,
    containsGluten: true,
    confidence: "high",
    notes: "Béchamel typically contains butter, milk, and flour.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Alfredo",
    normalizedName: "alfredo",
    aliases: ["alfredo sauce"],
    containsDairy: true,
    confidence: "high",
    notes: "Alfredo sauce is dairy-based.",
    source: "manual",
    verified: true,
  },

  // EGG CORE
  {
    ingredientName: "Egg",
    normalizedName: "egg",
    aliases: [
      "eggs",
      "poached eggs",
      "fried eggs",
      "egg mimosa",
      "eggs benedict",
      "cheesy frittata display",
      "frittata",
    ],
    containsEgg: true,
    confidence: "high",
    notes: "Egg-based items contain egg allergen.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Hollandaise",
    normalizedName: "hollandaise",
    aliases: ["hollandaise sauce", "lemon hollandaise sauce"],
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Hollandaise usually contains egg and butter.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Aioli",
    normalizedName: "aioli",
    aliases: ["garlic aioli"],
    containsEgg: true,
    confidence: "medium",
    notes: "Aioli typically contains egg; recipe should be confirmed.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Mayonnaise",
    normalizedName: "mayonnaise",
    aliases: ["mayo"],
    containsEgg: true,
    confidence: "high",
    notes: "Mayonnaise typically contains egg.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Meringue",
    normalizedName: "meringue",
    containsEgg: true,
    confidence: "high",
    notes: "Meringue contains egg whites.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Brioche",
    normalizedName: "brioche",
    containsEgg: true,
    containsDairy: true,
    containsGluten: true,
    confidence: "medium",
    notes: "Brioche often contains egg, dairy, and wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "French Toast",
    normalizedName: "french toast",
    containsEgg: true,
    containsDairy: true,
    containsGluten: true,
    confidence: "medium",
    notes: "French toast usually contains egg, dairy, and bread.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Crepe",
    normalizedName: "crepe",
    aliases: ["crepes"],
    containsEgg: true,
    containsDairy: true,
    containsGluten: true,
    confidence: "medium",
    notes: "Crepes often contain egg, dairy, and flour.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Carbonara",
    normalizedName: "carbonara",
    aliases: ["carbonara sauce"],
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Carbonara often contains egg and cheese.",
    source: "manual",
    verified: true,
  },

  // GLUTEN CORE
  {
    ingredientName: "Flour",
    normalizedName: "flour",
    aliases: ["wheat flour", "all purpose flour"],
    containsGluten: true,
    confidence: "high",
    notes: "Standard flour is assumed to be wheat flour.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Breadcrumbs",
    normalizedName: "breadcrumbs",
    aliases: ["bread crumbs", "panko", "croutons", "garlic croutons"],
    containsGluten: true,
    confidence: "high",
    notes: "Breadcrumbs, panko, and croutons typically contain wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Bread",
    normalizedName: "bread",
    aliases: [
      "garlic bread",
      "sliced breads",
      "assorted rolls",
      "fresh baked assorted rolls",
      "bread rolls",
      "mini bagels",
      "bagels",
      "croissants",
      "danishes",
      "muffins",
      "popovers",
      "everything popovers",
      "corn bread",
      "pizza bagels",
      "hotdogs",
      "toast",
      "toaster",
      "breaded chicken cutlet",
    ],
    containsGluten: true,
    confidence: "high",
    notes: "Standard breads and baked goods are assumed to contain gluten.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Pasta",
    normalizedName: "pasta",
    aliases: [
      "penne",
      "orecchiette",
      "ziti",
      "radiatore pasta",
      "pasta a la vodka",
      "penne vodka",
      "penne pasta bolognese",
      "gnocchi",
      "ravioli",
      "lasagna",
      "couscous",
    ],
    containsGluten: true,
    confidence: "medium",
    notes: "Standard pasta is assumed to contain gluten unless stated otherwise.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Pizza",
    normalizedName: "pizza",
    aliases: ["pizza crust", "margherita pizza", "sausage pizza"],
    containsGluten: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Pizza usually contains wheat crust and often cheese.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Roux",
    normalizedName: "roux",
    containsGluten: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Traditional roux uses flour and butter.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Wonton",
    normalizedName: "wonton",
    aliases: ["wonton wrapper"],
    containsGluten: true,
    confidence: "high",
    notes: "Wonton wrappers usually contain wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Dumpling",
    normalizedName: "dumpling",
    aliases: ["dumplings"],
    containsGluten: true,
    confidence: "medium",
    notes: "Dumpling wrappers often contain wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Farro",
    normalizedName: "farro",
    containsGluten: true,
    confidence: "high",
    notes: "Farro contains gluten.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Barley",
    normalizedName: "barley",
    containsGluten: true,
    confidence: "high",
    notes: "Barley contains gluten.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Seitan",
    normalizedName: "seitan",
    containsGluten: true,
    confidence: "high",
    notes: "Seitan is concentrated wheat gluten.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tempura",
    normalizedName: "tempura",
    aliases: ["tempura batter"],
    containsGluten: true,
    containsEgg: true,
    confidence: "medium",
    notes: "Tempura batter often contains wheat and may contain egg.",
    source: "manual",
    verified: true,
  },

  // SOY CORE
  {
    ingredientName: "Soy Sauce",
    normalizedName: "soy sauce",
    aliases: ["shoyu"],
    containsSoy: true,
    containsGluten: true,
    confidence: "high",
    notes: "Standard soy sauce usually contains soy and wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Teriyaki",
    normalizedName: "teriyaki",
    aliases: ["teriyaki sauce", "teriyaki glaze"],
    containsSoy: true,
    containsGluten: true,
    confidence: "medium",
    notes: "Teriyaki often includes soy sauce and may contain wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Miso",
    normalizedName: "miso",
    aliases: ["miso glaze"],
    containsSoy: true,
    confidence: "high",
    notes: "Miso contains soy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tofu",
    normalizedName: "tofu",
    containsSoy: true,
    confidence: "high",
    notes: "Tofu contains soy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Edamame",
    normalizedName: "edamame",
    containsSoy: true,
    confidence: "high",
    notes: "Edamame contains soy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Hoisin",
    normalizedName: "hoisin",
    aliases: ["hoisin sauce"],
    containsSoy: true,
    confidence: "medium",
    notes: "Hoisin often contains soy; recipe may vary.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tamari",
    normalizedName: "tamari",
    containsSoy: true,
    confidence: "high",
    notes: "Tamari contains soy; gluten status may vary by brand.",
    source: "manual",
    verified: true,
  },

  // NUT CORE
  {
    ingredientName: "Pesto",
    normalizedName: "pesto",
    aliases: ["mint pesto", "basil pesto", "pesto cream"],
    containsNuts: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Traditional pesto often contains nuts and parmesan.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Almond",
    normalizedName: "almond",
    aliases: ["almonds", "almond milk"],
    containsNuts: true,
    confidence: "high",
    notes: "Almond is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Walnut",
    normalizedName: "walnut",
    aliases: ["walnuts"],
    containsNuts: true,
    confidence: "high",
    notes: "Walnut is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Pecan",
    normalizedName: "pecan",
    aliases: ["pecans"],
    containsNuts: true,
    confidence: "high",
    notes: "Pecan is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Peanut",
    normalizedName: "peanut",
    aliases: ["peanuts"],
    containsNuts: true,
    confidence: "high",
    notes: "Peanut is treated as nut allergen in this app.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Pine Nuts",
    normalizedName: "pine nuts",
    aliases: ["pine nut"],
    containsNuts: true,
    confidence: "high",
    notes: "Pine nuts are treated as nut allergen in this app.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Pistachio",
    normalizedName: "pistachio",
    aliases: ["pistachios"],
    containsNuts: true,
    confidence: "high",
    notes: "Pistachio is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Hazelnut",
    normalizedName: "hazelnut",
    aliases: ["hazelnuts"],
    containsNuts: true,
    confidence: "high",
    notes: "Hazelnut is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Cashew",
    normalizedName: "cashew",
    aliases: ["cashews"],
    containsNuts: true,
    confidence: "high",
    notes: "Cashew is a tree nut.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Marzipan",
    normalizedName: "marzipan",
    containsNuts: true,
    confidence: "high",
    notes: "Marzipan is almond-based.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Praline",
    normalizedName: "praline",
    confidence: "medium",
    containsNuts: true,
    notes: "Praline often contains nuts; recipe may vary.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Nuts",
    normalizedName: "nuts",
    aliases: ["assorted nuts", "mixed nuts", "candied nuts"],
    containsNuts: true,
    confidence: "high",
    notes: "Generic nuts are treated as nut allergen.",
    source: "manual",
    verified: true,
  },

  // SHELLFISH CORE
  {
    ingredientName: "Shrimp",
    normalizedName: "shrimp",
    aliases: ["shrimps", "jumbo shrimps", "poached jumbo shrimps", "prawn", "prawns"],
    containsShellfish: true,
    confidence: "high",
    notes: "Shrimp and prawns are shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Crab",
    normalizedName: "crab",
    aliases: ["crab meat", "crab cake", "crab cakes"],
    containsShellfish: true,
    confidence: "high",
    notes: "Crab is shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Lobster",
    normalizedName: "lobster",
    aliases: ["lobster meat"],
    containsShellfish: true,
    confidence: "high",
    notes: "Lobster is shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Scallop",
    normalizedName: "scallop",
    aliases: ["scallops", "bay scallops"],
    containsShellfish: true,
    confidence: "high",
    notes: "Scallop is shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Mussel",
    normalizedName: "mussel",
    aliases: ["mussels"],
    containsShellfish: true,
    confidence: "high",
    notes: "Mussels are shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Oyster",
    normalizedName: "oyster",
    aliases: ["oysters", "east coast oysters"],
    containsShellfish: true,
    confidence: "high",
    notes: "Oysters are shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Clam",
    normalizedName: "clam",
    aliases: ["clams", "littleneck clams"],
    containsShellfish: true,
    confidence: "high",
    notes: "Clams are shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Crawfish",
    normalizedName: "crawfish",
    aliases: ["crayfish"],
    containsShellfish: true,
    confidence: "high",
    notes: "Crawfish is shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Langoustine",
    normalizedName: "langoustine",
    aliases: ["langoustines"],
    containsShellfish: true,
    confidence: "high",
    notes: "Langoustine is shellfish.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Calamari",
    normalizedName: "calamari",
    confidence: "medium",
    notes: "Calamari is seafood; shellfish classification may vary by policy. Review manually if needed.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Octopus",
    normalizedName: "octopus",
    confidence: "medium",
    notes: "Octopus is seafood; shellfish classification may vary by policy. Review manually if needed.",
    source: "manual",
    verified: true,
  },

  // SESAME CORE
  {
    ingredientName: "Sesame Oil",
    normalizedName: "sesame oil",
    aliases: ["toasted sesame oil"],
    containsSesame: true,
    confidence: "high",
    notes: "Sesame oil contains sesame.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tahini",
    normalizedName: "tahini",
    containsSesame: true,
    confidence: "high",
    notes: "Tahini contains sesame.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Sesame Seeds",
    normalizedName: "sesame seeds",
    aliases: ["sesame seed", "benne seeds"],
    containsSesame: true,
    confidence: "high",
    notes: "Sesame seeds contain sesame.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Halva",
    normalizedName: "halva",
    containsSesame: true,
    confidence: "medium",
    notes: "Halva is commonly sesame-based.",
    source: "manual",
    verified: true,
  },

  // BREAKFAST / BRUNCH / BANQUET ITEMS
  {
    ingredientName: "Belgian Waffles",
    normalizedName: "belgian waffles",
    aliases: ["waffles", "pancakes", "belgian waffles and pancakes"],
    containsGluten: true,
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Waffles and pancakes commonly contain flour, egg, and dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Huevos Rancheros",
    normalizedName: "huevos rancheros",
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Huevos rancheros often contains egg and may contain dairy depending on toppings.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Queso Fresco",
    normalizedName: "queso fresco",
    containsDairy: true,
    confidence: "high",
    notes: "Queso fresco contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Bread Pudding",
    normalizedName: "bread pudding",
    containsGluten: true,
    containsEgg: true,
    containsDairy: true,
    confidence: "high",
    notes: "Bread pudding typically contains bread, egg, and dairy.",
    source: "manual",
    verified: true,
  },

  // ITALIAN / CATERING MENU TERMS
  {
    ingredientName: "Vodka Sauce",
    normalizedName: "vodka sauce",
    aliases: ["a la vodka sauce"],
    containsDairy: true,
    confidence: "medium",
    notes: "Vodka sauce often contains cream.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Bolognese",
    normalizedName: "bolognese",
    aliases: ["prosciutto bolognese"],
    containsDairy: true,
    confidence: "low",
    notes: "Bolognese may include dairy depending on recipe; review if needed.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Cannoli",
    normalizedName: "cannoli",
    aliases: ["cannolis"],
    containsGluten: true,
    containsDairy: true,
    confidence: "high",
    notes: "Cannoli shells usually contain wheat and filling contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tiramisu",
    normalizedName: "tiramisu",
    containsGluten: true,
    containsDairy: true,
    containsEgg: true,
    confidence: "high",
    notes: "Tiramisu commonly contains ladyfingers, mascarpone, and egg.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Panna Cotta",
    normalizedName: "panna cotta",
    containsDairy: true,
    confidence: "high",
    notes: "Panna cotta typically contains dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Cheesecake",
    normalizedName: "cheese cake",
    aliases: ["cheesecake", "ny style cheese cake", "new york style cheesecake"],
    containsDairy: true,
    containsEgg: true,
    containsGluten: true,
    confidence: "high",
    notes: "Cheesecake commonly contains dairy, egg, and crust with gluten.",
    source: "manual",
    verified: true,
  },

  // DESSERT / BAKERY
  {
    ingredientName: "Cookie",
    normalizedName: "cookie",
    aliases: ["cookies", "brownies", "blondies", "cupcakes", "cake pops", "carrot cake pops"],
    containsGluten: true,
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Cookies and similar baked desserts commonly contain gluten, egg, and dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Muffin",
    normalizedName: "muffin",
    aliases: ["muffins", "mini muffins"],
    containsGluten: true,
    containsEgg: true,
    containsDairy: true,
    confidence: "medium",
    notes: "Muffins commonly contain gluten, egg, and dairy.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Croissant",
    normalizedName: "croissant",
    aliases: ["croissants"],
    containsGluten: true,
    containsDairy: true,
    confidence: "high",
    notes: "Croissants usually contain wheat and butter.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Danish",
    normalizedName: "danish",
    aliases: ["danishes"],
    containsGluten: true,
    containsDairy: true,
    containsEgg: true,
    confidence: "medium",
    notes: "Danish pastries often contain gluten, dairy, and egg.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Bagel",
    normalizedName: "bagel",
    aliases: ["bagels", "mini bagels"],
    containsGluten: true,
    confidence: "high",
    notes: "Bagels are assumed to contain wheat unless stated otherwise.",
    source: "manual",
    verified: true,
  },

  // PROTEIN / SEAFOOD / OTHER COMMON MENU ITEMS
  {
    ingredientName: "Salmon",
    normalizedName: "salmon",
    aliases: ["smoked salmon"],
    confidence: "medium",
    notes: "Salmon is fish, not one of the currently tracked contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Anchovy",
    normalizedName: "anchovy",
    aliases: ["anchovies"],
    confidence: "medium",
    notes: "Anchovy is fish, not one of the currently tracked contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Tuna",
    normalizedName: "tuna",
    confidence: "medium",
    notes: "Tuna is fish, not one of the currently tracked contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Duck",
    normalizedName: "duck",
    aliases: ["smoked duck"],
    confidence: "medium",
    notes: "Duck itself is not one of the tracked allergen contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Prosciutto",
    normalizedName: "prosciutto",
    confidence: "medium",
    notes: "Prosciutto itself is not one of the tracked allergen contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Salami",
    normalizedName: "salami",
    aliases: ["capicola"],
    confidence: "medium",
    notes: "Cured meats are not one of the tracked allergen contains-tags in this MVP.",
    source: "manual",
    verified: true,
  },

  // AMBIGUOUS HELPER TERMS
  {
    ingredientName: "Tortilla",
    normalizedName: "tortilla",
    aliases: ["corn tortilla", "flour tortilla", "flour and corn tortilla"],
    containsGluten: true,
    confidence: "medium",
    notes: "Flour tortillas contain gluten; mixed tortilla descriptions should be reviewed carefully.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Soy Glaze",
    normalizedName: "soy glaze",
    aliases: ["soy reduction"],
    containsSoy: true,
    containsGluten: true,
    confidence: "medium",
    notes: "Soy glazes often contain soy sauce and may contain wheat.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Sesame Crusted",
    normalizedName: "sesame crusted",
    containsSesame: true,
    confidence: "medium",
    notes: "Sesame-crusted items likely contain sesame.",
    source: "manual",
    verified: true,
  },
  {
    ingredientName: "Nut Crusted",
    normalizedName: "nut crusted",
    containsNuts: true,
    confidence: "medium",
    notes: "Nut-crusted items likely contain nuts.",
    source: "manual",
    verified: true,
  },
];

async function upsertRule(rule: IngredientSeed) {
  const payload = {
    ingredientName: rule.ingredientName,
    normalizedName: rule.normalizedName,
    containsGluten: rule.containsGluten ?? false,
    containsDairy: rule.containsDairy ?? false,
    containsEgg: rule.containsEgg ?? false,
    containsSoy: rule.containsSoy ?? false,
    containsNuts: rule.containsNuts ?? false,
    containsShellfish: rule.containsShellfish ?? false,
    containsSesame: rule.containsSesame ?? false,
    isVegetarian: rule.isVegetarian ?? null,
    isVegan: rule.isVegan ?? null,
    confidence: rule.confidence ?? null,
    notes: rule.notes ?? null,
    source: rule.source ?? "manual",
    verified: rule.verified ?? true,
  };

  await prisma.ingredientRule.upsert({
    where: { normalizedName: rule.normalizedName },
    update: payload,
    create: payload,
  });

  if (Array.isArray(rule.aliases)) {
    for (const alias of rule.aliases) {
      const normalizedAlias = alias.trim().toLowerCase();
      if (!normalizedAlias) continue;

      await prisma.ingredientRule.upsert({
        where: { normalizedName: normalizedAlias },
        update: {
          ...payload,
          ingredientName: alias,
          normalizedName: normalizedAlias,
          notes: rule.notes
            ? `${rule.notes} Alias for ${rule.ingredientName}.`
            : `Alias for ${rule.ingredientName}.`,
        },
        create: {
          ...payload,
          ingredientName: alias,
          normalizedName: normalizedAlias,
          notes: rule.notes
            ? `${rule.notes} Alias for ${rule.ingredientName}.`
            : `Alias for ${rule.ingredientName}.`,
        },
      });
    }
  }
}

async function main() {
  for (const rule of INGREDIENT_RULES) {
    await upsertRule(rule);
  }

  console.log(
    `Seeded ${INGREDIENT_RULES.length} base ingredient rules plus aliases.`
  );
}

main()
  .catch((error) => {
    console.error("Chef Bot seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });